version: "3.9"

  #services:
  #  prefect:
  #    image: prefecthq/prefect:2-python3.10-conda
  #    restart: always
  #    entrypoint: ["prefect", "server", "start"]
  #    environment:
  #      - PREFECT_ORION_API_HOST=0.0.0.0
  #    ports:
  #      - 4200:4200
services:
  build_report:
    build: .
    network_mode: "host"
    depends_on:
      - prefect

  prefect:
    image: prefecthq/prefect:2-python3.10
    network_mode: "host"
    restart: always
    entrypoint: ["prefect", "server", "start"]
